<a href="https://colab.research.google.com/github/shaikfarzana12/MLOPS/blob/main/feaststudent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 24.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 65.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 34.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [2]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [3]:
from google.colab import files

uploaded = files.upload()

Saving cse_skill_dataset (4).csv to cse_skill_dataset (4).csv

In [4]:
import pandas as pd

df = pd.read_csv("cse_skill_dataset (4).csv")

print(df.head())
print(df.shape)

   Student_ID   Specialization  CGPA  Programming_Skill_Score  \
0  CSE2027001  Cloud Computing  8.25                       33
1  CSE2027002         Core CSE  6.50                       33
2  CSE2027003  Cloud Computing  6.17                       73
3  CSE2027004              IoT  7.81                       78
4  CSE2027005              IoT  6.74                       40

   Communication_Skill_Score  Certifications_Count Internship_Experience  \
0                         65                     1                   Yes
1                         55                     5                    No
2                         43                     0                    No
3                         40                     4                    No
4                         59                     6                   Yes

   Projects_Completed  DSA_Platform_Rating Placement_Training_Attended  \
0                   2                 1009                         Yes
1                   3                 1719                          No
2                   1                 1535                          No
3                   5                 1982                         Yes
4                   6                 1369                          No

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0                 84                           42                     51
1                 50                           84                     77
2                 63                           91                     52
3                 38                           42                     92
4                 76                           50                     73

   Curriculum_Industry_Alignment_Score Skill_Gap_Label
0                                94.26             Yes
1                                94.85             Yes
2                                65.22             Yes
3                                65.44              No
4                                82.93             Yes
(150, 15)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [5]:
print(df.columns)

Index(['Student_ID', 'Specialization', 'CGPA', 'Programming_Skill_Score',
       'Communication_Skill_Score', 'Certifications_Count',
       'Internship_Experience', 'Projects_Completed', 'DSA_Platform_Rating',
       'Placement_Training_Attended', 'Soft_Skills_Score',
       'Curriculum_Coverage_Percent', 'Industry_Demand_Score',
       'Curriculum_Industry_Alignment_Score', 'Skill_Gap_Label'],
      dtype='object')

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Student_ID                           150 non-null    object
 1   Specialization                       150 non-null    object
 2   CGPA                                 150 non-null    float64
 3   Programming_Skill_Score              150 non-null    int64
 4   Communication_Skill_Score            150 non-null    int64
 5   Certifications_Count                 150 non-null    int64
 6   Internship_Experience                150 non-null    object
 7   Projects_Completed                   150 non-null    int64
 8   DSA_Platform_Rating                  150 non-null    int64
 9   Placement_Training_Attended          150 non-null    object
 10  Soft_Skills_Score                    150 non-null    int64
 11  Curriculum_Coverage_Percent          150 non-null    int64
 12  Industry_Demand_Score                150 non-null    int64
 13  Curriculum_Industry_Alignment_Score  150 non-null    float64
 14  Skill_Gap_Label                      150 non-null    object
dtypes: float64(2), int64(8), object(5)
memory usage: 17.7+ KB
None

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [7]:
print(df.isnull().sum())

Student_ID                             0
Specialization                         0
CGPA                                   0
Programming_Skill_Score                0
Communication_Skill_Score              0
Certifications_Count                   0
Internship_Experience                  0
Projects_Completed                     0
DSA_Platform_Rating                    0
Placement_Training_Attended            0
Soft_Skills_Score                      0
Curriculum_Coverage_Percent            0
Industry_Demand_Score                  0
Curriculum_Industry_Alignment_Score    0
Skill_Gap_Label                        0
dtype: int64

In [8]:
print(df.head())

   Student_ID   Specialization  CGPA  Programming_Skill_Score  \
0  CSE2027001  Cloud Computing  8.25                       33
1  CSE2027002         Core CSE  6.50                       33
2  CSE2027003  Cloud Computing  6.17                       73
3  CSE2027004              IoT  7.81                       78
4  CSE2027005              IoT  6.74                       40

   Communication_Skill_Score  Certifications_Count Internship_Experience  \
0                         65                     1                   Yes
1                         55                     5                    No
2                         43                     0                    No
3                         40                     4                    No
4                         59                     6                   Yes

   Projects_Completed  DSA_Platform_Rating Placement_Training_Attended  \
0                   2                 1009                         Yes
1                   3                 1719                          No
2                   1                 1535                          No
3                   5                 1982                         Yes
4                   6                 1369                          No

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0                 84                           42                     51
1                 50                           84                     77
2                 63                           91                     52
3                 38                           42                     92
4                 76                           50                     73

   Curriculum_Industry_Alignment_Score Skill_Gap_Label
0                                94.26             Yes
1                                94.85             Yes
2                                65.22             Yes
3                                65.44              No
4                                82.93             Yes

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [9]:
# Entity
df["student_id"] = df["Student_ID"].astype(str)

# Derived feature 1
df["cgpa_percent"] = (
    df["CGPA"] * 10
).astype("float32")

# Derived feature 2
df["skill_readiness_score"] = (
    df[
        [
            "cgpa_percent",
            "Programming_Skill_Score",
            "Communication_Skill_Score",
            "Soft_Skills_Score",
            "Curriculum_Coverage_Percent",
            "Industry_Demand_Score",
            "Curriculum_Industry_Alignment_Score"
        ]
    ].mean(axis=1)
).astype("float32")

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
df["specialization_encoded"] = (
    df["Specialization"]
    .astype("category")
    .cat.codes
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [11]:
df.head()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label,student_id,cgpa_percent,skill_readiness_score,specialization_encoded
0,CSE2027001,Cloud Computing,8.25,33,65,1,Yes,2,1009,Yes,84,42,51,94.26,Yes,CSE2027001,82.500000,64.537140,1
1,CSE2027002,Core CSE,6.50,33,55,5,No,3,1719,No,50,84,77,94.85,Yes,CSE2027002,65.000000,65.550003,2
2,CSE2027003,Cloud Computing,6.17,73,43,0,No,1,1535,No,63,91,52,65.22,Yes,CSE2027003,61.700001,64.131432,1
3,CSE2027004,IoT,7.81,78,40,4,No,5,1982,Yes,38,42,92,65.44,No,CSE2027004,78.099998,61.934284,5
4,CSE2027005,IoT,6.74,40,59,6,Yes,6,1369,No,76,50,73,82.93,Yes,CSE2027005,67.400002,64.047142,5

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [12]:
base_time = pd.Timestamp(
    "2026-01-01",
    tz="UTC"
)

df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        range(len(df)),
        unit="s"
    )
)

df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   student_id           event_timestamp         created_timestamp
0  CSE2027001 2026-01-01 00:00:00+00:00 2026-01-01 00:00:01+00:00
1  CSE2027002 2026-01-01 00:00:01+00:00 2026-01-01 00:00:02+00:00
2  CSE2027003 2026-01-01 00:00:02+00:00 2026-01-01 00:00:03+00:00
3  CSE2027004 2026-01-01 00:00:03+00:00 2026-01-01 00:00:04+00:00
4  CSE2027005 2026-01-01 00:00:04+00:00 2026-01-01 00:00:05+00:00

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [14]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "cgpa_percent",
        "Programming_Skill_Score",
        "Communication_Skill_Score",
        "Certifications_Count",
        "Internship_Experience",
        "Projects_Completed",
        "DSA_Platform_Rating",
        "Placement_Training_Attended",
        "Soft_Skills_Score",
        "Curriculum_Coverage_Percent",
        "Industry_Demand_Score",
        "Curriculum_Industry_Alignment_Score",
        "specialization_encoded",
        "skill_readiness_score"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [15]:
label_df = df[
    [
        "student_id",
        "event_timestamp",
        "Skill_Gap_Label"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [16]:
print("Feature data:")
display(feature_df.head())

print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,cgpa_percent,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,specialization_encoded,skill_readiness_score
0,CSE2027001,2026-01-01 00:00:00+00:00,2026-01-01 00:00:01+00:00,82.500000,33,65,1,Yes,2,1009,Yes,84,42,51,94.26,1,64.537140
1,CSE2027002,2026-01-01 00:00:01+00:00,2026-01-01 00:00:02+00:00,65.000000,33,55,5,No,3,1719,No,50,84,77,94.85,2,65.550003
2,CSE2027003,2026-01-01 00:00:02+00:00,2026-01-01 00:00:03+00:00,61.700001,73,43,0,No,1,1535,No,63,91,52,65.22,1,64.131432
3,CSE2027004,2026-01-01 00:00:03+00:00,2026-01-01 00:00:04+00:00,78.099998,78,40,4,No,5,1982,Yes,38,42,92,65.44,5,61.934284
4,CSE2027005,2026-01-01 00:00:04+00:00,2026-01-01 00:00:05+00:00,67.400002,40,59,6,Yes,6,1369,No,76,50,73,82.93,5,64.047142

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   student_id           event_timestamp Skill_Gap_Label
0  CSE2027001 2026-01-01 00:00:00+00:00             Yes
1  CSE2027002 2026-01-01 00:00:01+00:00             Yes
2  CSE2027003 2026-01-01 00:00:02+00:00             Yes
3  CSE2027004 2026-01-01 00:00:03+00:00              No
4  CSE2027005 2026-01-01 00:00:04+00:00             Yes

In [17]:
label_df["skill_gap"] = (
    label_df["Skill_Gap_Label"]
    .map({
        "No": 0,
        "Yes": 1
    })
    .astype("int64")
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [18]:
display(label_df.head())

   student_id           event_timestamp Skill_Gap_Label  skill_gap
0  CSE2027001 2026-01-01 00:00:00+00:00             Yes          1
1  CSE2027002 2026-01-01 00:00:01+00:00             Yes          1
2  CSE2027003 2026-01-01 00:00:02+00:00             Yes          1
3  CSE2027004 2026-01-01 00:00:03+00:00              No          0
4  CSE2027005 2026-01-01 00:00:04+00:00             Yes          1

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [19]:
import os

repo_path = "/content/student_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [20]:
feature_df.to_parquet(
    f"{repo_path}/data/student_features.parquet",
    index=False
)

In [21]:
feature_store_yaml = """
project: student_skill_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [22]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)


# -----------------------------
# ENTITY
# -----------------------------

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="CSE student"
)


# -----------------------------
# DATA SOURCE
# -----------------------------

student_source = FileSource(
    name="student_source",
    path="data/student_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)


# -----------------------------
# FEATURE VIEW
# -----------------------------

student_feature_view = FeatureView(
    name="student_skill_features",
    entities=[student],

    ttl=timedelta(days=36500),

    schema=[
        Field(name="cgpa_percent", dtype=Float32),
        Field(name="Programming_Skill_Score", dtype=Int64),
        Field(name="Communication_Skill_Score", dtype=Int64),
        Field(name="Certifications_Count", dtype=Int64),
        Field(name="Internship_Experience", dtype=Int64),
        Field(name="Projects_Completed", dtype=Int64),
        Field(name="DSA_Platform_Rating", dtype=Int64),
        Field(name="Placement_Training_Attended", dtype=Int64),
        Field(name="Soft_Skills_Score", dtype=Int64),
        Field(name="Curriculum_Coverage_Percent", dtype=Int64),
        Field(name="Industry_Demand_Score", dtype=Int64),
        Field(name="Curriculum_Industry_Alignment_Score", dtype=Int64),
        Field(name="specialization_encoded", dtype=Int64),
        Field(name="skill_readiness_score", dtype=Float32),
    ],

    source=student_source,

    online=True
)


# -----------------------------
# FEATURE SERVICE
# -----------------------------

student_feature_service = FeatureService(
    name="skill_gap_model_service",
    features=[
        student_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

In [23]:
!find /content/student_feast -maxdepth 2 -type f

/content/student_feast/data/student_features.parquet
/content/student_feast/features.py
/content/student_feast/feature_store.yaml

In [24]:
%cd /content/student_feast

/content/student_feast

In [25]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/student_feast/features.py:22: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name student_skill_project defined in feature_store.yaml
Applying changes for project student_skill_project
Created project student_skill_project
Created entity student
Created feature view student_skill_features
Created feature service skill_gap_model_service

Created sqlite table student_skill_project_student_skill_features

In [26]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION    TYPE
student  CSE student    ValueType.UNKNOWN

In [27]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                    ENTITIES     TYPE         ENABLED    STATE
student_skill_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [28]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/student_feast"
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [29]:
feature_service = store.get_feature_service(
    "skill_gap_model_service"
)

In [30]:
feature_service = store.get_feature_service(
    "skill_gap_model_service"
)

In [31]:
entity_df = label_df[
    [
        "student_id",
        "event_timestamp",
        "skill_gap"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [32]:
display(entity_df.head())

   student_id           event_timestamp  skill_gap
0  CSE2027001 2026-01-01 00:00:00+00:00          1
1  CSE2027002 2026-01-01 00:00:01+00:00          1
2  CSE2027003 2026-01-01 00:00:02+00:00          1
3  CSE2027004 2026-01-01 00:00:03+00:00          0
4  CSE2027005 2026-01-01 00:00:04+00:00          1

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [33]:
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [34]:
display(training_data.head())

,student_id,event_timestamp,skill_gap,cgpa_percent,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,specialization_encoded,skill_readiness_score
0,CSE2027001,2026-01-01 00:00:00+00:00,1,82.500000,33,65,1,Yes,2,1009,Yes,84,42,51,94.26,1,64.537140
1,CSE2027002,2026-01-01 00:00:01+00:00,1,65.000000,33,55,5,No,3,1719,No,50,84,77,94.85,2,65.550003
2,CSE2027003,2026-01-01 00:00:02+00:00,1,61.700001,73,43,0,No,1,1535,No,63,91,52,65.22,1,64.131432
3,CSE2027004,2026-01-01 00:00:03+00:00,0,78.099998,78,40,4,No,5,1982,Yes,38,42,92,65.44,5,61.934284
4,CSE2027005,2026-01-01 00:00:04+00:00,1,67.400002,40,59,6,Yes,6,1369,No,76,50,73,82.93,5,64.047142

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [35]:
feature_columns = [
    "cgpa_percent",
    "Programming_Skill_Score",
    "Communication_Skill_Score",
    "Certifications_Count",
    "Internship_Experience",
    "Projects_Completed",
    "DSA_Platform_Rating",
    "Placement_Training_Attended",
    "Soft_Skills_Score",
    "Curriculum_Coverage_Percent",
    "Industry_Demand_Score",
    "Curriculum_Industry_Alignment_Score",
    "specialization_encoded",
    "skill_readiness_score"
]

In [36]:
X = training_data[feature_columns]

y = training_data["skill_gap"]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [39]:
# Features = everything except the target
X = training_data[feature_columns].copy()

# Target = Skill Gap
y = training_data["skill_gap"].copy()

print("X columns:")
print(X.columns.tolist())

print("\nTarget values:")
print(y.unique())

X columns:
['cgpa_percent', 'Programming_Skill_Score', 'Communication_Skill_Score', 'Certifications_Count', 'Internship_Experience', 'Projects_Completed', 'DSA_Platform_Rating', 'Placement_Training_Attended', 'Soft_Skills_Score', 'Curriculum_Coverage_Percent', 'Industry_Demand_Score', 'Curriculum_Industry_Alignment_Score', 'specialization_encoded', 'skill_readiness_score']

Target values:
[1 0]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [40]:
print(X.dtypes)

cgpa_percent                           float32
Programming_Skill_Score                  int64
Communication_Skill_Score                int64
Certifications_Count                     int64
Internship_Experience                   object
Projects_Completed                       int64
DSA_Platform_Rating                      int64
Placement_Training_Attended             object
Soft_Skills_Score                        int64
Curriculum_Coverage_Percent              int64
Industry_Demand_Score                    int64
Curriculum_Industry_Alignment_Score    float64
specialization_encoded                   int64
skill_readiness_score                  float32
dtype: object

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [41]:
for col in X.columns:
    if X[col].dtype == "object":
        print(col, X[col].unique())

Internship_Experience ['Yes' 'No']
Placement_Training_Attended ['Yes' 'No']

In [42]:
from sklearn.preprocessing import LabelEncoder

X = X.copy()

for col in X.select_dtypes(include="object").columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

print(X.dtypes)

cgpa_percent                           float32
Programming_Skill_Score                  int64
Communication_Skill_Score                int64
Certifications_Count                     int64
Internship_Experience                    int64
Projects_Completed                       int64
DSA_Platform_Rating                      int64
Placement_Training_Attended              int64
Soft_Skills_Score                        int64
Curriculum_Coverage_Percent              int64
Industry_Demand_Score                    int64
Curriculum_Industry_Alignment_Score    float64
specialization_encoded                   int64
skill_readiness_score                  float32
dtype: object

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [43]:
print(X.head())

   cgpa_percent  Programming_Skill_Score  Communication_Skill_Score  \
0     82.500000                       33                         65
1     65.000000                       33                         55
2     61.700001                       73                         43
3     78.099998                       78                         40
4     67.400002                       40                         59

   Certifications_Count  Internship_Experience  Projects_Completed  \
0                     1                      1                   2
1                     5                      0                   3
2                     0                      0                   1
3                     4                      0                   5
4                     6                      1                   6

   DSA_Platform_Rating  Placement_Training_Attended  Soft_Skills_Score  \
0                 1009                            1                 84
1                 1719                            0                 50
2                 1535                            0                 63
3                 1982                            1                 38
4                 1369                            0                 76

   Curriculum_Coverage_Percent  Industry_Demand_Score  \
0                           42                     51
1                           84                     77
2                           91                     52
3                           42                     92
4                           50                     73

   Curriculum_Industry_Alignment_Score  specialization_encoded  \
0                                94.26                       1
1                                94.85                       2
2                                65.22                       1
3                                65.44                       5
4                                82.93                       5

   skill_readiness_score
0              64.537140
1              65.550003
2              64.131432
3              61.934284
4              64.047142

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [44]:
y = y.astype(int)

print(y.head())
print(y.unique())

0    1
1    1
2    1
3    0
4    1
Name: skill_gap, dtype: int64
[1 0]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (120, 14)
X_test: (30, 14)
y_train: (120,)
y_test: (30,)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [46]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("Model trained successfully! 🎉")

Model trained successfully! 🎉

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [47]:
predictions = model.predict(X_test)

print(predictions)

[0 0 1 0 1 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 0 0 1 0 0]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [48]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 76.67 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [49]:
predictions = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [50]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 76.67 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [51]:
print(df["event_timestamp"].min())
print(df["event_timestamp"].max())

2026-01-01 00:00:00+00:00
2026-01-01 00:02:29+00:00

In [52]:
%cd /content/student_feast

/content/student_feast

In [53]:
!feast materialize \
    2026-01-01T00:00:00 \
    2026-01-01T00:03:00

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2026-01-01 00:00:00+00:00 to 2026-01-01 00:03:00+00:00 into the sqlite online store.

student_skill_features:
Traceback (most recent call last):
  File "/usr/local/bin/feast", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1569, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1490, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1970, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1353, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 907, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/cli/cli.py", line 411, in materialize_command
    store.materialize(
  File "/usr/local/lib/python3.12/dist-packages/feast/feature_store.py", line 2396, in materialize
    provider.materialize_single_feature_view(
  File "/usr/local/lib/python3.12/dist-packages/feast/infra/passthrough_provider.py", line 468, in materialize_single_feature_view
    raise e
  File "/usr/local/lib/python3.12/dist-packages/feast/infra/compute_engines/local/compute.py", line 84, in _materialize_one
    plan.execute(context)
  File "/usr/local/lib/python3.12/dist-packages/feast/infra/compute_engines/dag/plan.py", line 51, in execute
    output = node.execute(context)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/infra/compute_engines/local/nodes.py", line 391, in execute
    rows_to_write = _convert_arrow_to_proto(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/utils.py", line 423, in _convert_arrow_to_proto
    return _convert_arrow_fv_to_proto(table, feature_view, join_keys)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/utils.py", line 445, in _convert_arrow_fv_to_proto
    proto_values_by_column = _columns_to_proto_values(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/utils.py", line 376, in _columns_to_proto_values
    result[column] = python_values_to_proto_values(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/type_map.py", line 1416, in python_values_to_proto_values
    proto_values = _python_value_to_proto_value(value_type, values)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/type_map.py", line 1266, in _python_value_to_proto_value
    return _convert_scalar_values_to_proto(feast_value_type, values, scalar_sample)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/type_map.py", line 1099, in _convert_scalar_values_to_proto
    out.append(ProtoValue(**{field_name: func(value)}))
                                         ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/feast/type_map.py", line 620, in <lambda>
    else int(x)
         ^^^^^^
ValueError: invalid literal for int() with base 10: 'Yes'

In [54]:
print(
    df["event_timestamp"].min(),
    df["event_timestamp"].max()
)

2026-01-01 00:00:00+00:00 2026-01-01 00:02:29+00:00

In [55]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {
            "student_id": "CSE2027001"
        }
    ]
).to_dict()

In [56]:
print(online_features)

{'student_id': ['CSE2027001'], 'Placement_Training_Attended': [None], 'Soft_Skills_Score': [None], 'cgpa_percent': [None], 'Industry_Demand_Score': [None], 'Internship_Experience': [None], 'Projects_Completed': [None], 'DSA_Platform_Rating': [None], 'skill_readiness_score': [None], 'Communication_Skill_Score': [None], 'Programming_Skill_Score': [None], 'specialization_encoded': [None], 'Curriculum_Industry_Alignment_Score': [None], 'Certifications_Count': [None], 'Curriculum_Coverage_Percent': [None]}

In [57]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,Placement_Training_Attended,Soft_Skills_Score,cgpa_percent,Industry_Demand_Score,Internship_Experience,Projects_Completed,DSA_Platform_Rating,skill_readiness_score,Communication_Skill_Score,Programming_Skill_Score,specialization_encoded,Curriculum_Industry_Alignment_Score,Certifications_Count,Curriculum_Coverage_Percent
0,CSE2027001,None,None,None,None,None,None,None,None,None,None,None,None,None,None

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [58]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [59]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [61]:
X_online = online_df[
    feature_columns
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [62]:
prediction = final_model.predict(
    X_online
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [63]:
print(
    "Predicted Skill Gap:",
    "Yes" if prediction[0] == 1 else "No"
)

Predicted Skill Gap: No

In [64]:
student_ids = [
    "CSE2027001",
    "CSE2027002",
    "CSE2027003",
    "CSE2027004"
]

online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {"student_id": sid}
        for sid in student_ids
    ]
).to_dict()

online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,Placement_Training_Attended,Soft_Skills_Score,cgpa_percent,Industry_Demand_Score,Internship_Experience,Projects_Completed,DSA_Platform_Rating,skill_readiness_score,Communication_Skill_Score,Programming_Skill_Score,specialization_encoded,Curriculum_Industry_Alignment_Score,Certifications_Count,Curriculum_Coverage_Percent
0,CSE2027001,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,CSE2027002,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,CSE2027003,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,CSE2027004,None,None,None,None,None,None,None,None,None,None,None,None,None,None

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [65]:
online_df["predicted_skill_gap"] = (
    final_model.predict(
        online_df[feature_columns]
    )
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [66]:
online_df["predicted_skill_gap"] = (
    online_df["predicted_skill_gap"]
    .map({
        0: "No",
        1: "Yes"
    })
)

In [67]:
display(
    online_df[
        [
            "student_id",
            "predicted_skill_gap"
        ]
    ]
)

   student_id predicted_skill_gap
0  CSE2027001                  No
1  CSE2027002                  No
2  CSE2027003                  No
3  CSE2027004                  No

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)