<a href="https://colab.research.google.com/github/shaikfarzana12/MLOPS/blob/main/student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("cse_skill_dataset (4).csv")

In [ ]:
df.head()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
0,CSE2027001,Cloud Computing,8.25,33,65,1,Yes,2,1009,Yes,84,42,51,94.26,Yes
1,CSE2027002,Core CSE,6.50,33,55,5,No,3,1719,No,50,84,77,94.85,Yes
2,CSE2027003,Cloud Computing,6.17,73,43,0,No,1,1535,No,63,91,52,65.22,Yes
3,CSE2027004,IoT,7.81,78,40,4,No,5,1982,Yes,38,42,92,65.44,No
4,CSE2027005,IoT,6.74,40,59,6,Yes,6,1369,No,76,50,73,82.93,Yes

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1Cn9YcFcbu5PftxgUWTgHvFqlyOrvVzN6QbHmLKNlozs/edit#gid=0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Student_ID                           150 non-null    object
 1   Specialization                       150 non-null    object
 2   CGPA                                 150 non-null    float64
 3   Programming_Skill_Score              150 non-null    int64
 4   Communication_Skill_Score            150 non-null    int64
 5   Certifications_Count                 150 non-null    int64
 6   Internship_Experience                150 non-null    object
 7   Projects_Completed                   150 non-null    int64
 8   DSA_Platform_Rating                  150 non-null    int64
 9   Placement_Training_Attended          150 non-null    object
 10  Soft_Skills_Score                    150 non-null    int64
 11  Curriculum_Coverage_Percent          150 non-null    int64
 12  Industry_Demand_Score                150 non-null    int64
 13  Curriculum_Industry_Alignment_Score  150 non-null    float64
 14  Skill_Gap_Label                      150 non-null    object
dtypes: float64(2), int64(8), object(5)
memory usage: 17.7+ KB

In [ ]:
df.shape

(150, 15)

In [ ]:
df.columns

Index(['Student_ID', 'Specialization', 'CGPA', 'Programming_Skill_Score',
       'Communication_Skill_Score', 'Certifications_Count',
       'Internship_Experience', 'Projects_Completed', 'DSA_Platform_Rating',
       'Placement_Training_Attended', 'Soft_Skills_Score',
       'Curriculum_Coverage_Percent', 'Industry_Demand_Score',
       'Curriculum_Industry_Alignment_Score', 'Skill_Gap_Label'],
      dtype='object')

In [ ]:
df.isnull().sum()

Student_ID                             0
Specialization                         0
CGPA                                   0
Programming_Skill_Score                0
Communication_Skill_Score              0
Certifications_Count                   0
Internship_Experience                  0
Projects_Completed                     0
DSA_Platform_Rating                    0
Placement_Training_Attended            0
Soft_Skills_Score                      0
Curriculum_Coverage_Percent            0
Industry_Demand_Score                  0
Curriculum_Industry_Alignment_Score    0
Skill_Gap_Label                        0
dtype: int64

In [ ]:
num_cols = df.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipykernel_1666/974458584.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [ ]:
cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_1666/2213161713.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

Student_ID                             0
Specialization                         0
CGPA                                   0
Programming_Skill_Score                0
Communication_Skill_Score              0
Certifications_Count                   0
Internship_Experience                  0
Projects_Completed                     0
DSA_Platform_Rating                    0
Placement_Training_Attended            0
Soft_Skills_Score                      0
Curriculum_Coverage_Percent            0
Industry_Demand_Score                  0
Curriculum_Industry_Alignment_Score    0
Skill_Gap_Label                        0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [ ]:
df.head()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
0,0,1,8.25,33,65,1,1,2,1009,1,84,42,51,94.26,1
1,1,2,6.50,33,55,5,0,3,1719,0,50,84,77,94.85,1
2,2,1,6.17,73,43,0,0,1,1535,0,63,91,52,65.22,1
3,3,5,7.81,78,40,4,0,5,1982,1,38,42,92,65.44,0
4,4,5,6.74,40,59,6,1,6,1369,0,76,50,73,82.93,1

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1h0EE1rCRfLGVsuDRM1bLyEUzczbqpIZRc4miS4dFlM4/edit#gid=0

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)

In [ ]:
df_scaled.head()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
0,-1.720542,-0.829113,0.584654,-1.498603,-0.039630,-0.952040,1.098127,-0.741653,-1.315530,1.128152,0.948016,-1.765440,-1.657581,0.820423,1.0
1,-1.697448,-0.231195,-0.837565,-1.498603,-0.561080,0.990899,-0.910642,-0.347157,0.557092,-0.886405,-0.672253,0.683321,0.100528,0.877547,1.0
2,-1.674353,-0.829113,-1.105755,0.407208,-1.186819,-1.437774,-0.910642,-1.136150,0.071793,-0.886405,-0.052738,1.091448,-1.589962,-1.991217,1.0
3,-1.651258,1.562559,0.227067,0.645435,-1.343254,0.505164,-0.910642,0.441836,1.250753,1.128152,-1.244113,-1.765440,1.114821,-1.969916,-1.0
4,-1.628164,1.562559,-0.642518,-1.165086,-0.352500,1.476633,1.098127,0.836333,-0.366032,-0.886405,0.566777,-1.299010,-0.169951,-0.276542,1.0

In [ ]:
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

df = pd.read_csv("cse_skill_dataset (4).csv")

In [3]:
df.head()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
0,CSE2027001,Cloud Computing,8.25,33,65,1,Yes,2,1009,Yes,84,42,51,94.26,Yes
1,CSE2027002,Core CSE,6.50,33,55,5,No,3,1719,No,50,84,77,94.85,Yes
2,CSE2027003,Cloud Computing,6.17,73,43,0,No,1,1535,No,63,91,52,65.22,Yes
3,CSE2027004,IoT,7.81,78,40,4,No,5,1982,Yes,38,42,92,65.44,No
4,CSE2027005,IoT,6.74,40,59,6,Yes,6,1369,No,76,50,73,82.93,Yes

In [4]:
# Features (input columns)
X = df.drop("Skill_Gap_Label", axis=1)

# Target column
y = df["Skill_Gap_Label"]

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (150, 14)
y Shape: (150,)

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (120, 14)
Testing Features: (30, 14)
Training Labels: (120,)
Testing Labels: (30,)

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [7]:
numerical_columns = X.select_dtypes(include=['int64','float64']).columns

categorical_columns = X.select_dtypes(include=['object']).columns

In [8]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

In [9]:
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [10]:
preprocessor = ColumnTransformer([
    ('num', num_pipeline, numerical_columns),
    ('cat', cat_pipeline, categorical_columns)
])

In [11]:
X_processed = preprocessor.fit_transform(X)

In [12]:
print(X_processed.shape)

(150, 170)

In [13]:
processed_df = pd.DataFrame(X_processed.toarray() if hasattr(X_processed, "toarray") else X_processed)

In [14]:
processed_df.to_csv("processed_dataset.csv", index=False)

In [15]:
from google.colab import files

files.download("processed_dataset.csv")

In [16]:
print(df.head())

   Student_ID   Specialization  CGPA  Programming_Skill_Score  \
0  CSE2027001  Cloud Computing  8.25                       33
1  CSE2027002         Core CSE  6.50                       33
2  CSE2027003  Cloud Computing  6.17                       73
3  CSE2027004              IoT  7.81                       78
4  CSE2027005              IoT  6.74                       40

   Communication_Skill_Score  Certifications_Count Internship_Experience  \
0                         65                     1                   Yes
1                         55                     5                    No
2                         43                     0                    No
3                         40                     4                    No
4                         59                     6                   Yes

   Projects_Completed  DSA_Platform_Rating Placement_Training_Attended  \
0                   2                 1009                         Yes
1                   3                 1719                          No
2                   1                 1535                          No
3                   5                 1982                         Yes
4                   6                 1369                          No

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0                 84                           42                     51
1                 50                           84                     77
2                 63                           91                     52
3                 38                           42                     92
4                 76                           50                     73

   Curriculum_Industry_Alignment_Score Skill_Gap_Label
0                                94.26             Yes
1                                94.85             Yes
2                                65.22             Yes
3                                65.44              No
4                                82.93             Yes

In [18]:
import pandas as pd

df = pd.read_csv("cse_skill_dataset (4).csv")

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col].astype(str))

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled = pd.DataFrame(
    scaler.fit_transform(df),
    columns=df.columns
)

In [21]:
print(df_scaled.head())

   Student_ID  Specialization      CGPA  Programming_Skill_Score  \
0   -1.720542       -0.829113  0.584654                -1.498603
1   -1.697448       -0.231195 -0.837565                -1.498603
2   -1.674353       -0.829113 -1.105755                 0.407208
3   -1.651258        1.562559  0.227067                 0.645435
4   -1.628164        1.562559 -0.642518                -1.165086

   Communication_Skill_Score  Certifications_Count  Internship_Experience  \
0                  -0.039630             -0.952040               1.098127
1                  -0.561080              0.990899              -0.910642
2                  -1.186819             -1.437774              -0.910642
3                  -1.343254              0.505164              -0.910642
4                  -0.352500              1.476633               1.098127

   Projects_Completed  DSA_Platform_Rating  Placement_Training_Attended  \
0           -0.741653            -1.315530                     1.128152
1           -0.347157             0.557092                    -0.886405
2           -1.136150             0.071793                    -0.886405
3            0.441836             1.250753                     1.128152
4            0.836333            -0.366032                    -0.886405

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0           0.948016                    -1.765440              -1.657581
1          -0.672253                     0.683321               0.100528
2          -0.052738                     1.091448              -1.589962
3          -1.244113                    -1.765440               1.114821
4           0.566777                    -1.299010              -0.169951

   Curriculum_Industry_Alignment_Score  Skill_Gap_Label
0                             0.820423              1.0
1                             0.877547              1.0
2                            -1.991217              1.0
3                            -1.969916             -1.0
4                            -0.276542              1.0

In [22]:
print(df.head())

   Student_ID  Specialization  CGPA  Programming_Skill_Score  \
0           0               1  8.25                       33
1           1               2  6.50                       33
2           2               1  6.17                       73
3           3               5  7.81                       78
4           4               5  6.74                       40

   Communication_Skill_Score  Certifications_Count  Internship_Experience  \
0                         65                     1                      1
1                         55                     5                      0
2                         43                     0                      0
3                         40                     4                      0
4                         59                     6                      1

   Projects_Completed  DSA_Platform_Rating  Placement_Training_Attended  \
0                   2                 1009                            1
1                   3                 1719                            0
2                   1                 1535                            0
3                   5                 1982                            1
4                   6                 1369                            0

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0                 84                           42                     51
1                 50                           84                     77
2                 63                           91                     52
3                 38                           42                     92
4                 76                           50                     73

   Curriculum_Industry_Alignment_Score  Skill_Gap_Label
0                                94.26                1
1                                94.85                1
2                                65.22                1
3                                65.44                0
4                                82.93                1

In [23]:
print(df_scaled.head())

   Student_ID  Specialization      CGPA  Programming_Skill_Score  \
0   -1.720542       -0.829113  0.584654                -1.498603
1   -1.697448       -0.231195 -0.837565                -1.498603
2   -1.674353       -0.829113 -1.105755                 0.407208
3   -1.651258        1.562559  0.227067                 0.645435
4   -1.628164        1.562559 -0.642518                -1.165086

   Communication_Skill_Score  Certifications_Count  Internship_Experience  \
0                  -0.039630             -0.952040               1.098127
1                  -0.561080              0.990899              -0.910642
2                  -1.186819             -1.437774              -0.910642
3                  -1.343254              0.505164              -0.910642
4                  -0.352500              1.476633               1.098127

   Projects_Completed  DSA_Platform_Rating  Placement_Training_Attended  \
0           -0.741653            -1.315530                     1.128152
1           -0.347157             0.557092                    -0.886405
2           -1.136150             0.071793                    -0.886405
3            0.441836             1.250753                     1.128152
4            0.836333            -0.366032                    -0.886405

   Soft_Skills_Score  Curriculum_Coverage_Percent  Industry_Demand_Score  \
0           0.948016                    -1.765440              -1.657581
1          -0.672253                     0.683321               0.100528
2          -0.052738                     1.091448              -1.589962
3          -1.244113                    -1.765440               1.114821
4           0.566777                    -1.299010              -0.169951

   Curriculum_Industry_Alignment_Score  Skill_Gap_Label
0                             0.820423              1.0
1                             0.877547              1.0
2                            -1.991217              1.0
3                            -1.969916             -1.0
4                            -0.276542              1.0

In [24]:
print("Missing Values Before:")
print(df.isnull().sum())

Missing Values Before:
Student_ID                             0
Specialization                         0
CGPA                                   0
Programming_Skill_Score                0
Communication_Skill_Score              0
Certifications_Count                   0
Internship_Experience                  0
Projects_Completed                     0
DSA_Platform_Rating                    0
Placement_Training_Attended            0
Soft_Skills_Score                      0
Curriculum_Coverage_Percent            0
Industry_Demand_Score                  0
Curriculum_Industry_Alignment_Score    0
Skill_Gap_Label                        0
dtype: int64

In [25]:
print("Missing Values After:")
print(df_scaled.isnull().sum())

Missing Values After:
Student_ID                             0
Specialization                         0
CGPA                                   0
Programming_Skill_Score                0
Communication_Skill_Score              0
Certifications_Count                   0
Internship_Experience                  0
Projects_Completed                     0
DSA_Platform_Rating                    0
Placement_Training_Attended            0
Soft_Skills_Score                      0
Curriculum_Coverage_Percent            0
Industry_Demand_Score                  0
Curriculum_Industry_Alignment_Score    0
Skill_Gap_Label                        0
dtype: int64

In [26]:
df.describe()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,74.500000,2.386667,7.530600,64.453333,65.760000,2.960000,0.453333,3.880000,1507.780000,0.44000,64.106667,72.280000,75.513333,85.786267,0.500000
std,43.445368,1.678073,1.234594,21.058750,19.241552,2.065634,0.499485,2.543369,380.417801,0.49805,21.054466,17.208988,14.838159,10.363094,0.501675
min,0.000000,0.000000,5.510000,30.000000,30.000000,0.000000,0.000000,0.000000,816.000000,0.00000,31.000000,41.000000,50.000000,57.530000,0.000000
25%,37.250000,1.000000,6.535000,45.250000,49.250000,1.000000,0.000000,2.000000,1202.500000,0.00000,48.000000,57.250000,63.000000,78.282500,0.000000
50%,74.500000,2.000000,7.375000,65.500000,65.000000,3.000000,0.000000,4.000000,1516.000000,0.00000,60.500000,74.500000,77.000000,87.825000,0.500000
75%,111.750000,4.000000,8.617500,82.000000,82.750000,5.000000,1.000000,6.000000,1832.500000,1.00000,83.000000,86.000000,88.000000,94.830000,1.000000
max,149.000000,5.000000,9.780000,100.000000,99.000000,6.000000,1.000000,8.000000,2188.000000,1.00000,100.000000,100.000000,100.000000,100.000000,1.000000

In [27]:
df_scaled.describe()

,Student_ID,Specialization,CGPA,Programming_Skill_Score,Communication_Skill_Score,Certifications_Count,Internship_Experience,Projects_Completed,DSA_Platform_Rating,Placement_Training_Attended,Soft_Skills_Score,Curriculum_Coverage_Percent,Industry_Demand_Score,Curriculum_Industry_Alignment_Score,Skill_Gap_Label
count,150.000000,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,150.000000,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02,150.00000
mean,0.000000,-2.072416e-17,2.723747e-16,5.921189e-18,-2.760755e-16,0.000000,-3.256654e-17,3.848773e-17,5.773160e-17,7.105427e-17,-1.332268e-16,-6.217249e-17,-1.421085e-16,-9.414691e-16,0.00000
std,1.003350,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.003350,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00,1.00335
min,-1.720542,-1.427031e+00,-1.642135e+00,-1.641539e+00,-1.864704e+00,-1.437774,-9.106417e-01,-1.530646e+00,-1.824566e+00,-8.864053e-01,-1.577697e+00,-1.823744e+00,-1.725201e+00,-2.735759e+00,-1.00000
25%,-0.860271,-8.291131e-01,-8.091207e-01,-9.149482e-01,-8.609134e-01,-0.952040,-9.106417e-01,-7.416534e-01,-8.051745e-01,-8.864053e-01,-7.675628e-01,-8.763067e-01,-8.461464e-01,-7.265113e-01,-1.00000
50%,0.000000,-2.311950e-01,-1.264556e-01,4.986873e-02,-3.963018e-02,0.019429,-9.106417e-01,4.733958e-02,2.168021e-02,-8.864053e-01,-1.718756e-01,1.294345e-01,1.005278e-01,1.973893e-01,0.00000
75%,0.860271,9.646412e-01,8.833199e-01,8.360159e-01,8.859430e-01,0.990899,1.098127e+00,8.363326e-01,8.564474e-01,1.128152e+00,9.003613e-01,7.999287e-01,8.443432e-01,8.756102e-01,1.00000
max,1.720542,1.562559e+00,1.828080e+00,1.693631e+00,1.733299e+00,1.476633,1.098127e+00,1.625326e+00,1.794077e+00,1.128152e+00,1.710496e+00,1.616182e+00,1.655778e+00,1.376167e+00,1.00000